name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
      env:
        VITE_STREAMELEMENTS_ENABLED: ${{ secrets.VITE_STREAMELEMENTS_ENABLED }}
        VITE_STREAMELEMENTS_JWT_TOKEN: ${{ secrets.VITE_STREAMELEMENTS_JWT_TOKEN }}
        VITE_STREAMELEMENTS_CHANNEL_ID: ${{ secrets.VITE_STREAMELEMENTS_CHANNEL_ID }}
        VITE_STREAMELEMENTS_TEST_MODE: ${{ secrets.VITE_STREAMELEMENTS_TEST_MODE }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist